### ISSUE TITLE
Build has failed after multiple attempts

### ISSUE THREAD

**Issue by AbbyBenson** [gbif/hp-bison#3]
@MattBlissett or @MortenHofft I could use your help if you have a moment to spare it. I seem to have irrevocably broken the build for hp-bison by linking incorrectly to an image (lesson learned!) and I'm not sure how to fix it. All the things I have tried to fix it have not worked and I don't know how to put the repo back to the version it was last week. Any assistance would be greatly appreciated!

**Comment by MattBlissett** [comment]
Hi Abby,

The image bluenose_shiner_FWC.jpg had a CMYK colour profile (meaning it was originally prepared for printing, rather than display on a screen — there are differences since screens can show a wider gamut of colours than typical for ink on paper).

A tool we used to compress images doesn't work with this, but since the Colombia portal had a similar problem a few weeks ago I've added a process to automatically convert the CMYK image to RGB.

(Deleting the image would also have fixed the build, or it could have been converted from CMYK→RGB in a graphics editor and re-uploaded.)

**Comment by AbbyBenson** [comment]
Thank you!
